export const BANDIT_RADIUS = 0.35;

export const PLAYER_RADIUS = 0.75;

export const BANDIT_INSIDE_RADIUS = BANDIT_RADIUS + ((PLAYER_RADIUS - BANDIT_RADIUS) / 3);

export const BANDIT_SCALE_GOAL = BANDIT_INSIDE_RADIUS / BANDIT_RADIUS;

export const BANDIT_RADIUS_DIFF = BANDIT_INSIDE_RADIUS - BANDIT_RADIUS;
